name: "commit-stage"
on: push
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: moustaphajr/config-service
  VERSION: latest
jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
      - name: "Set up JDK"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: "Build, unit tests and integration tests"
        run: |
          chmod +x mvnw 
          ./mvnw clean package
      - name: "Code vulnerability scanning"
        uses: anchore/scan-action@v4
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          output-format: sarif
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif
  package:
    name: "Build and Publish"
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
      security-events: write
    if: ${{github.ref=='refs/heads/main' || github.ref=='refs/heads/master'}}
    needs: [ build ]
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v4
      - name: "setup jdk"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: "build container image"
        run: |
          chmod +x mvnw 
          mvn spring-boot:build-image -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
      - name: "scan vulnerabilies"
        uses: anchore/scan-action@v4
        id: scan
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          fail-build: false
          output-format: sarif
      - name: "Upload vulnerability report"
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif
      - name: "login to registry"
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "push to registry"
        run: |
          docker push ${{env.REGISTRY}}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
